"""added password

Revision ID: c7c0d0df07d5
Revises: e2b6a9c7b7c7
Create Date: 2021-02-13 19:13:47.447388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c0d0df07d5'
down_revision = 'e2b6a9c7b7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('korisnik', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('korisnik', sa.Column('password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
